apiVersion: v1
kind: Service
metadata:
  name: menu-service
  labels:
    app: menu-service
spec:
  selector:
    app: menu-service
  ports:
  - port: 5025
    targetPort: 5025
    protocol: TCP
    name: http
  type: ClusterIP