apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: PAYMENT_SERVICE_URL
          value: "http://payment-service:5008"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:5020"
        - name: RESTAURANT_SERVICE_URL
          value: "http://restaurant-service:5000"