version: '3.8'

services:
  restaurant-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/restaurant-service
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  menu-service:
    build: ./menu-service
    ports:
      - "5001:5001"
    environment:
      - RESTAURANT_SERVICE_URL=http://restaurant-service:5000
    depends_on:
      - restaurant-service
      
